language: cpp

install:
  - sudo apt-get update
  - sudo apt-get install qt5-default qttools5-dev-tools

script:
  - qmake -project
  - qmake ./playerdemo/playerdemo.pro
  - make
  
  
 before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev
 - sudo apt-get install qt5-default qttools5-dev-tools

script:
 - qmake -project
 - qmake ./playerdemo/playerdemo.pro
 - make